releaseStoreFile=../vittam-internal-release.jks
releaseStorePassword=FRvwmpmLPhboxaCqxGpQSVQoTyY5xxrs
releaseKeyAlias=vittam-internal-release
releaseKeyPassword=FRvwmpmLPhboxaCqxGpQSVQoTyY5xxrs
debugStoreFile=../vittam-internal-debug.jks
debugStorePassword=txXZSSn0Gnr5afqg8moAUzkknNUuDg
debugKeyAlias=vittam-internal-debug
debugKeyPassword=txXZSSn0Gnr5afqg8moAUzkknNUuDg
