#!/usr/bin/env bash
# =============================================================================
# version.sh — Generate git.properties for ezStackflorisboard
#
# Outputs a Java properties file containing build metadata derived from git
# state. Used by the app at runtime to display version info.
#
# Usage:
#   ./scripts/version.sh [OUTPUT_PATH]
#
# Default output: app/src/main/resources/git.properties
# =============================================================================

set -euo pipefail

OUTPUT="${1:-app/src/main/resources/git.properties}"

# ---------------------------------------------------------------------------
# 1. Resolve latest v* tag and parse semver
# ---------------------------------------------------------------------------
LATEST_TAG=$(git describe --tags --match "v*" --abbrev=0 2>/dev/null || echo "")

if [[ -z "${LATEST_TAG}" ]]; then
    # No release tags yet — base version is 0.0.0, count all commits
    VERSION_RAW="0.0.0"
    COMMITS_SINCE=$(git rev-list HEAD --count 2>/dev/null || echo "0")
else
    VERSION_RAW="${LATEST_TAG#v}"   # strip leading 'v'
    COMMITS_SINCE=$(git rev-list "${LATEST_TAG}..HEAD" --count 2>/dev/null || echo "0")
fi

IFS='.' read -r MAJOR MINOR PATCH <<< "${VERSION_RAW}"
MAJOR="${MAJOR:-0}"
MINOR="${MINOR:-0}"
PATCH="${PATCH:-0}"

# ---------------------------------------------------------------------------
# 2. Commits since tag (build number) and auto-incremented patch for DEV
# ---------------------------------------------------------------------------
BUILD_NUMBER="${COMMITS_SINCE}"

# ---------------------------------------------------------------------------
# 3. Commit hashes
# ---------------------------------------------------------------------------
COMMIT_ABBREV=$(git rev-parse --short=7 HEAD 2>/dev/null || echo "0000000")
COMMIT_FULL=$(git rev-parse HEAD 2>/dev/null || echo "0000000000000000000000000000000000000000")

# ---------------------------------------------------------------------------
# 4. Dirty state detection
# ---------------------------------------------------------------------------
if git diff --quiet HEAD && git diff --cached --quiet HEAD 2>/dev/null; then
    DIRTY="false"
    DIRTY_STR=""
else
    DIRTY="true"
    DIRTY_STR="-dirty"
fi

# ---------------------------------------------------------------------------
# 5. Build mode: REL on dev/main/master, DEV on all other branches
# ---------------------------------------------------------------------------
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
if [[ "${BRANCH}" == "dev" || "${BRANCH}" == "main" || "${BRANCH}" == "master" ]]; then
    BUILD_MODE="REL"
else
    BUILD_MODE="DEV"
fi

# ---------------------------------------------------------------------------
# 6. Version string: REL uses tag version; DEV auto-increments patch
# ---------------------------------------------------------------------------
if [[ "${BUILD_MODE}" == "REL" ]]; then
    VERSION="${MAJOR}.${MINOR}.${PATCH}"
else
    # Auto-increment patch for every commit since last tag on dev branches
    DEV_PATCH=$(( PATCH + COMMITS_SINCE ))
    VERSION="${MAJOR}.${MINOR}.${DEV_PATCH}"
fi

# ---------------------------------------------------------------------------
# 7. Build timestamp (ISO 8601 UTC)
# ---------------------------------------------------------------------------
BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ---------------------------------------------------------------------------
# 8. Full version string: {BUILD_MODE}-{VERSION}{DIRTY_STR} ({COMMIT_HASH})
# ---------------------------------------------------------------------------
VERSION_FULL="${BUILD_MODE}-${VERSION}${DIRTY_STR} (${COMMIT_ABBREV})"

# ---------------------------------------------------------------------------
# 9. Write properties file
# ---------------------------------------------------------------------------
mkdir -p "$(dirname "${OUTPUT}")"

cat > "${OUTPUT}" <<EOF
# Generated by scripts/version.sh — DO NOT EDIT
# Generated at: ${BUILD_TIME}
git.build.version=${VERSION}
git.build.version.major=${MAJOR}
git.build.version.minor=${MINOR}
git.build.version.patch=${PATCH}
git.build.number=${BUILD_NUMBER}
git.commit.id.abbrev=${COMMIT_ABBREV}
git.commit.id.full=${COMMIT_FULL}
git.dirty=${DIRTY}
git.dirty.str=${DIRTY_STR}
git.build.mode=${BUILD_MODE}
git.branch=${BRANCH}
git.build.version.full=${VERSION_FULL}
git.build.time=${BUILD_TIME}
EOF

echo "[version.sh] ${VERSION_FULL} → ${OUTPUT}"
